using BarberOS.Domain.Common;

namespace BarberOS.Domain.Licensing;

/// <summary>
/// License generated by SuperAdmin to allow a barbershop to register.
/// Monetization: each license has an expiration date (days/months/years).
/// </summary>
public sealed class BarbershipLicense : BaseGlobalAuditableEntity
{
    private BarbershipLicense() { }

    public string Code { get; private set; } = string.Empty;
    public Guid? TenantId { get; private set; }
    public DateTimeOffset ExpiresAt { get; private set; }
    public string? Notes { get; private set; }

    public bool IsAssigned => TenantId.HasValue;
    public bool IsExpired(DateTimeOffset now) => ExpiresAt < now;
    public bool IsValid(DateTimeOffset now) => !IsExpired(now);

    public static BarbershipLicense Create(string code, DateTimeOffset expiresAt, string? notes = null) =>
        new() { Code = code.ToUpperInvariant(), ExpiresAt = expiresAt, Notes = notes };

    public void AssignToTenant(Guid tenantId)
    {
        if (IsAssigned) throw new InvalidOperationException("License already assigned.");
        TenantId = tenantId;
    }

    public void ExtendExpiration(DateTimeOffset newExpiry) => ExpiresAt = newExpiry;
}
